### ISSUE TITLE
no_std support?

### ISSUE THREAD

**Issue by whitequark** [withoutboats/fehler#12]
Can der Fehler, in principle (I see it's not implemented right now), work with `#![no_std]` and without `alloc`?

**Comment by yoshuawuyts** [comment]
My understanding is that the `std::error::Error` trait Der Fehler relies on doesn't work with `#[no_std]`, which in turn means this crate can't either.

**Comment by whitequark** [comment]
Makes sense.

**Comment by roblabla** [comment]
I don't see why this has to be, and IMO this is a valid concern. Snafu also relies on this trait today, but [there's an open PR](https://github.com/shepmaster/snafu/pull/138) to make it use its own trait in no_std context.

**Comment by dtolnay** [comment]
throw! / #\[throws(...)\] / Ok-wrapping could be available on no_std even without Exception.

**Comment by withoutboats** [comment]
Re-opening to track the fact that the macros could be no_std and think about what to do about this.

**Comment by withoutboats** [comment]
This should now be supported properly. :)
