### ISSUE TITLE
Clarify the role of context?

### ISSUE THREAD

**Issue by epage** [withoutboats/fehler#16]
In thinking about this topic, I guess there are both primary and secondary contexts for an error.
- Primary:  The problem that occurred that a user may downcast to.
  - e.g. Failed to open file
- Secondary: Information to help the user resolve the issue
  - Sometimes people might want to programmatically act upon it.  One common case I've seen is when it is unclear if the context has already been added, so you check and then add it later.
  - e.g. file path (if the original error didn't include it)

I get mixed signals of which role `Context` is supposed to fill
- `error` field is required, making it seem like it is only for Secondary or is Primary but limited to masking other errors
- `ContextError` treats the `context` as the payload of an error, as if it was Primary

One side effect of this is that the displayed error looks wonky with `Context`.  For example, I [previously looked at `failure`](https://epage.github.io/blog/2018/03/redefining-failure/) for a library I wrote.  The custom errors look like

```
Error: liquid: Expected whole number, found `fractional number`
  with:
    end=10.5
from: {% for i in (1..max) reversed %}
from: {% if "blue skies" == var %}
  with:
    var=10
```
The original error "liquid: Expected whole number, found `fractional number`" is the error someone should programmatically act on.  I then add two different kinds of contexts as we unwind the stack, "with"s for data inside a stack frame and "from" for a stack from location.

When considering this for `failure`, I would have gotten
```
Error: liquid: Expected whole number, found `fractional number`
cause: end=10.5
cause: {% for i in (1..max) reversed %}
cause: var=10
cause: {% if "blue skies" == var %}
```
(might have this inverted; can't remember)

Related to this is a point I raised in https://github.com/mgattozzi/terminator/issues/3 of whether we should treat the `cause` / `source` as user-visible context or internal debug data.  If I use `source` for context and my original error is a `std::io::Error` which might not be user-friendly, I need to make choice of displaying it anyways or intentionally dropping it.

**Comment by withoutboats** [comment]
This isn't how context is intended to be used. It's modeled on the original use of a similar concept in cargo, in which a low level error like an IO error is wrapped in programmer-defined meaningful context, you can get something like (the exact text is obviously made up by me here):

```rust
Could not execute `cargo build`

caused by:
    0. Could not read Cargo.toml for this project
    1. File not found.
```

Neither of the ways you intended to use it seem to map well to this model. You want something different.
