### ISSUE TITLE
How do exceptions propagate?

### ISSUE THREAD

**Issue by paulstelian97** [withoutboats/fehler#17]
If I throw an exception in a function what happens in the calling function? If it's not a throwing function it will receive a Result but if it is, what happens? Receiving a Result in that case may make exceptions much less powerful.

**Comment by ArekPiekarz** [comment]
The confusion comes from a fact that this library gives new names to old things, names which have a different meaning in other languages. Rust doesn't have exceptions*, it uses Result values; it doesn't throw them, it only returns them like normal data. The mechanism of propagation of Fehler's "exceptions" is the same as for Results, they won't automatically go up the stack if you don't handle them.

* To be fair it has one type of exception - for panicking, but it's treated as an unrecoverable error.

**Comment by paulstelian97** [comment]
Alright, kinda expected this answer. And yeah, I guess I could make it an issue due to the misleading naming. It's just a nice macro to hide away the fact that Result<> is used and that is all.

If you call a function which throws and the caller is also such a macro, would the call just notice a Result<> or would more special treatment be done? Such as automatic insertion of ? operators.

**Comment by withoutboats** [comment]
> If you call a function which throws and the caller is also such a macro, would the call just notice a Result<> or would more special treatment be done? Such as automatic insertion of ? operators.

You have to use `?` just like always. Annotating every function call that could throw an error is a great aspect of Rust's design.

The `#[throws]` macro just:

- Modifies the return type in the signature of the function to return a result
- Wraps every return expression (including the implicit tail return) in an `Ok`
