### ISSUE TITLE
Consider renaming `error!` to avoid collision with `log::error!`

### ISSUE THREAD

**Issue by ErichDonGubler** [withoutboats/fehler#22]
As a person who uses Rust in production, it was confusing at first to see an `error!` macro defined by `fehler`. I understand that this can easily be handled in Rust 2018 by simply renaming imports:

```rust
use log::error as log_error;
// ...or, alternatively:
use fehler::error as throw_err;
```

...but it'd be nice to remove this papercut altogether and not force people to pick a solution. I'm not partial to what the symbol name ends up being -- just wanted to point out the issue!

**Comment by withoutboats** [comment]
Personally, I would recommend accessing at least one of these under its full path - you dont have to import anything, you can just write `log::error!()`. However, I'll consider renaming it so there's no issue.

**Comment by withoutboats** [comment]
Closing because this library just won't expose this macro
