### ISSUE TITLE
Where did Exception go?

### ISSUE THREAD

**Issue by mashedcode** [withoutboats/fehler#33]
I really liked `Exception`. Why was it removed in #26? Was it moved to another create? If not can I at least have it behind a feature flag if the goal is to make it more lightweight?

There also seems to be a new crate because of this change called [fehler_more](https://github.com/jedisct1/rust-fehler-more). Which just exports everything from the old version of the fehler crate. That's obviously terrible but proves that other people want to have `Exception`, etc. as well.

The immediate fix would be to simply stick with `fehler = "1.0.0-alpha.1"`

**Comment by withoutboats** [comment]
See here: https://github.com/withoutboats/fehler/issues/20#issuecomment-554434443

I discovered anyhow and realized that Exception and everything related to it was basically the exact same code as the anyhow crate. dtolnay is a better maintainer than me, there's no reason to duplicate that work, and I'm much more interested in experimenting with the throws attribute. If you liked exception, you should use anyhow's Error type, which is basically the same thing.

**Comment by mashedcode** [comment]
Thanks! Sorry for not looking through the issues properly.

**Comment by withoutboats** [comment]
No worries! The issue name doesn't suggest it's about this at all and I didn't link to it from the PR.
