### ISSUE TITLE
Are there any plans to support "x86_64-unknown-linux-musl"?

### ISSUE THREAD

**Issue by saks** [withoutboats/fehler#41]
When I build my project under alpine linux I get this message:
```
error: cannot produce proc-macro for `fehler-macros v1.0.0` as the target `x86_64-unknown-linux-musl` does not support these crate types
```
Please suggest if there is any workaround.
Thank you.

**Comment by ubnt-intrepid** [comment]
@saks The musl targets are statically linked to the native C runtime by default and you should explicitly disable the linking as follows (related issue: https://github.com/rust-lang/cargo/issues/7563):

```shell-session
$ RUSTFLAGS="-C target-feature=-crt-static" cargo build
```

Note: this workaround was no longer needed by https://github.com/rust-lang/rust/pull/69519 and the patch is contained in 1.44.0 (the current beta channel).

**Comment by withoutboats** [comment]
Thanks for finding the solution to this @ubnt-intrepid. This isn't an issue with fehler specifically, so I'll close it.

**Comment by saks** [comment]
Thanks for the context and explanation @ubnt-intrepid !
