### ISSUE TITLE
catch macro? 

### ISSUE THREAD

**Issue by tmccombs** [withoutboats/fehler#44]
Are there any plans for adding a `catch!` macro that would allow doing something like

```rust
let result: Result<i64> = catch!{
  let y = f1()?;
  let z = f2()?;
  if cond(z) {
    throw!(SomeError);
  }
  y + z
};
```

The simplest way to do this would be to add support for closures to the `throws` macro, and add a `catch!` macro like:

```
macro_rules! catch {
  ($($tts:tt)*) => { (#[throws(_)] || {$($tts)*})() };
}
```

But it isn't perfect, since a return inside the catch would behave in an unexpected way (return from the hidden closure instead of the outer function) and lifetimes might cause issues as well.

A better solution would be to make `catch!` a procedural macro that wraps the body in labeled scope, and transforms any `throw!` or `?` to use a labeled break with value instead of a return. And wraps the final value of the expression. I'm not sure how feasible that is.

**Comment by withoutboats** [comment]
There's an unstable feature that implements exactly this behavior! It's called try blocks: https://doc.rust-lang.org/nightly/unstable-book/language-features/try-blocks.html

**Comment by tmccombs** [comment]
oh, cool. I saw the RFC for that but must have missed that it was merged.
