### ISSUE TITLE
#[throws] on methods ending with "loop" warns about "unreachable expression"

### ISSUE THREAD

**Issue by samoylovfp** [withoutboats/fehler#53]
```rust
#[fehler::throws]
fn main() {
    potentially_failing_operation()?;
    loop {
        potentially_failing_operation()?;
    }
}
```

Results in a warning
```rust
  --> src/main.rs:5:1
   |
5  |   #[fehler::throws]
   |   ^^^^^^^^^^^^^^^^^ unreachable expression
...
8  | /     loop {
9  | |         potentially_failing_operation()?;
10 | |     }
   | |_____- any code following this expression is unreachable

```
Expected to be no warning.

I'll try to dig into the source to see if this is possible/trivial to fix.

Script for easy reproduction
```bash
cargo new fehler-unreachable
cd fehler-unreachable
echo 'fehler = "*"' >> Cargo.toml

echo '
#[derive(Debug)]
struct Error;

#[fehler::throws]
fn main() {
    loop {
    }
}
' > src/main.rs

cargo check
```

P.S.
Thanks for the awesome crate, really cleans up the code!

**Comment by samoylovfp** [comment]
First naive approach is to not add a return-wrapping when there is a `loop`.
It fails when there is this case
```rust
loop {
break
}
```

My next thought would be to see if we can somehow re-use the piece of code that determines if the loop is breakable or not.

**Comment by withoutboats** [comment]
There's a fix to a lot of unreachable code errors that's in git master but not on crates.io yet. Can you adjust your dependency to point to this git repository and confirm if this error still occurs?

**Comment by samoylovfp** [comment]
Master version produces no warning. Thank you!
