### ISSUE TITLE
Am i misusing the library ?

### ISSUE THREAD

**Issue by shika-blyat** [withoutboats/fehler#54]
I have this method
```rust
    #[throws(i32)]
    fn literal(&mut self) -> Literal<'a> {
        match self.peek() {
            Some(Token {
                kind: lit @ (TokenKind::Num(_) | TokenKind::Bool(_) | TokenKind::Unit),
                range,
            }) => Literal {
                pos: range.clone(),
                kind: match lit {
                    TokenKind::Num(n) => LiteralKind::Num(*n),
                    TokenKind::Bool(b) => LiteralKind::Bool(*b),
                    TokenKind::Unit => LiteralKind::Unit,
                    _ => unreachable!(),
                },
            },
            _ => throw!(5),
        }
    }
```
and i get, when i try to compile my code:
```rust
error: custom attribute panicked
  --> src\parser\parser.rs:18:5
   |
18 |     #[throws(i32)]
   |     ^^^^^^^^^^^^^^
   |
   = help: message: #[throws] attribute can only be applied to functions and methods
```

**Comment by dtolnay** [comment]
This probably requires someone to implement https://github.com/dtolnay/syn/issues/758.

**Comment by dtolnay** [comment]
To clarify: it looks like you are using it right but `lit @ (TokenKind::Num(_) | TokenKind::Bool(_) | TokenKind::Unit)` (or-pattern syntax) is new and not well supported by libraries.

This obviously isn't great but it would work changed to:

```rust
    Some(Token { kind: lit @ TokenKind::Num(_), range })
    | Some(Token { kind: lit @ TokenKind::Bool(_), range })
    | Some(Token { kind: lit @ TokenKind::Unit, range }) => {
```

**Comment by shika-blyat** [comment]
Okay, tyvm for the answer 😄. If this is not related at all to fehler, i guess i should close this ?

**Comment by withoutboats** [comment]
Closing with this note: while this isn't related to fehler, it highlights a limitation of implementing sugar like this through proc macros: they fall out of sync with the grammar of the language and end up not supporting all features.
