### ISSUE TITLE
Does Fehler have any abstraction over std::error::Error?

### ISSUE THREAD

**Issue by sanbox-irl** [withoutboats/fehler#59]
Hello!

Some other error handling crates, like anyhow, have abstractions over std::error::Error (or custom error types in older crates). Does Fehler have something like that, or should I be used std::error::Error myself, or should I be using another crate that wraps around that? By that question, I mean what would seem to cause the least friction in using the library?

Thank you very much and apologies for submitting a question as an issue!

**Comment by ijackson** [comment]
I'm using fehler with both anyhow and thiserror.  It works well with either. fehler doesn't get involved in what your error type is, so that's a separate question and if you want the features of anyhow or thiserror you'll want to use those crates along with fehler.

**Comment by sanbox-irl** [comment]
Oh yeah that's what I thought. i'll close this up
