### ISSUE TITLE
Consider supporting lazily constructed context on Result or context on Exception

### ISSUE THREAD

**Issue by dtolnay** [withoutboats/fehler#9]
The fehler::Context::context impl on Result looks like a performance hazard for context that is potentially expensive to construct.

```rust
use fehler::{throws, Context};
use std::path::Path;

#[throws]
fn f(_path: &Path) {}

fn main() {
    let path = Path::new("/");
    let _ = f(path).context(format!("failed to f {}", path.display()));
}
```

Would you consider something like `f(path).with_context(|| ...)` or `f(path).map_err(|ex| ex.context(...))`?

**Comment by withoutboats** [comment]
Yea seems fine, I see two ways to do this, and I'm open to adding both:

* A lazy version of `context` (your `with_context`)
* A constructor for `Exception` that takes a context as well as a source error, so you can do `map_err(|e| Exception::with_context(e, ""))`.

But maybe `in_context`, which is 2 characters shorter and also a bit goofier.

**Comment by withoutboats** [comment]
I've added `with_context`, the callback it takes is `FnOnce(&E) -> C`, so you can view the error while setting up the context if necessary. Keeping this open to ask for feedback: should there be a constructor on `Exception` as well?

**Comment by dtolnay** [comment]
I would recommend having the pair of APIs shown in my original comment.

On `Result`:

```rust
fn with_context<C, F>(self, context: F) -> Result<T, Exception>
where
    C: Display + Send + Sync + 'static,
    F: FnOnce() -> C;
```

On `Exception`:

```rust
fn context<C>(self, context: C) -> Exception
where
    C: Display + Send + Sync + 'static;
```

I find the with_context method added in #19 to be annoying because in my experience most context is standalone and doesn't need the `e` so writing `|_| ...` is unpleasant, and the rest of the time `map_err` + `.context(...)` is clearer anyway.

Regarding a constructor `Exception::with_context(e, "...")`, I would prefer to stick with `e.context("...")` when e is Exception and `Exception::new(e).context("...")` otherwise, which is shorter and clearer.

**Comment by withoutboats** [comment]
The only difference between `FnOnce(&E) -> C` and `FnOnce() -> C` is `|_|` vs `||`. I balk at finding the single underscore there a problem.

**Comment by withoutboats** [comment]
I'm open to adding context as a method on exception instead of a ctor but I do think it will be unclear to people that they can do `Exception::from(error).context("")`

**Comment by dtolnay** [comment]
Typing `|_|` isn't a problem but reading/reviewing is. Ignored closure parameters always take extra effort on the part of the reader to work out what they mean because there is no variable name or type there as a guide.

Since context needing access to the previous error is so uncommon, it would be better to optimize for readability. By using `FnOnce() -> C` the overwhelmingly common case is more readable and the rare case will use `map_err` which is widely understood to take the prev error and do a thing with it to produce a new error.

**Comment by withoutboats** [comment]
Closing because I'm going to delete this code and recommend anyhow instead.
